import { BarChart3, Target, Crosshair, RotateCcw, Activity, GitCompare, ShieldCheck } from "lucide-react"

function ModelEvaluation() {
 return <div className="info-page reinvented-page evaluation-v2">
  <header className="v2-hero"><div><span className="v2-kicker">03 / MODEL AUDIT</span><h1>Model Performance</h1><p>Evaluation results of the Random Forest classifier on the insurance fraud detection dataset.</p></div><div className="audit-mark"><span>TEST SET</span><b>RF-42</b></div></header>

  <section className="scoreboard"><div className="score-primary"><span>ACCURACY</span><strong>77.91%</strong><p>Overall proportion of correct predictions.</p></div><div className="score-stack"><div><Target size={18}/><span>PRECISION</span><b>92.65%</b></div><div><Activity size={18}/><span>RECALL</span><b>10.82%</b></div><div><BarChart3 size={18}/><span>F1 SCORE</span><b>19.38%</b></div></div></section>

  <section className="evaluation-overview"><div className="v2-section-title"><span>READ THE RESULTS</span><h2>Evaluation overview</h2></div><div className="overview-copy"><p>The Random Forest classifier was evaluated using the test portion of the dataset. Multiple classification metrics were considered to understand how well the model identifies fraudulent and non-fraudulent claims.</p><p>The model achieved an accuracy of 77.91% and a precision of 92.65%. Its recall was 10.82%, while the F1-score was 19.38%. These metrics provide a more detailed view of model behaviour than accuracy alone.</p></div></section>

  <section className="metric-cards"><div className="v2-section-title"><span>METRIC BREAKDOWN</span><h2>What the numbers mean</h2></div><div className="metric-grid-v2">{[[Target,"Accuracy","Measures the proportion of total predictions that were classified correctly.","77.91%"],[Crosshair,"Precision","Measures how many of the claims predicted as fraudulent were actually fraudulent.","92.65%"],[Activity,"Recall","Measures how many of the actual fraudulent claims were correctly identified by the model.","10.82%"],[BarChart3,"F1 Score","Combines precision and recall into a single metric and provides a balance between the two.","19.38%"]].map(([Icon,title,desc,value])=><article key={title}><div className="metric-top"><Icon size={19}/><span>{title}</span><b>{value}</b></div><p>{desc}</p></article>)}</div></section>

  <section className="interpretation"><div className="interpretation-head"><ShieldCheck size={24}/><div><span>PERFORMANCE INTERPRETATION</span><h2>Precision vs recall</h2></div></div><div className="interpretation-grid"><article><b>High Precision</b><p>The precision of 92.65% indicates that when the model predicts a claim as fraudulent, a high proportion of those predictions are correct.</p></article><article><b>Low Recall</b><p>The recall of 10.82% indicates that the model identifies only a relatively small proportion of the fraudulent claims present in the test data.</p></article></div><p className="interpretation-note">This difference between precision and recall is important when interpreting the model. Accuracy by itself does not fully describe fraud-detection performance, so the other evaluation metrics should also be considered.</p></section>

  <section className="checks-v2"><div className="v2-section-title"><span>VALIDATION CHECKS</span><h2>Additional evaluation</h2></div><div className="checks-grid">{[[Target,"Stratified Train-Test Split","The dataset was divided into 80% training and 20% testing data using stratification for the target classes."],[RotateCcw,"5-Fold Cross-Validation","Five-fold cross-validation was performed to examine model performance across different portions of the dataset."],[GitCompare,"Model Comparison","Logistic Regression and Decision Tree models were also considered during the model development process."],[ShieldCheck,"Overfitting Check","Training and testing performance were examined to check for differences that could indicate overfitting."]].map(([Icon,title,desc])=><article key={title}><Icon size={20}/><b>{title}</b><p>{desc}</p></article>)}</div></section>
  <div className="v2-note"><BarChart3 size={18}/><p>Accuracy should not be considered in isolation. Precision, recall and F1-score provide additional information about how the classifier behaves when identifying fraudulent claims.</p></div>
 </div>
}
export default ModelEvaluation
